zuul:
  routes:
    service-provider:
      path: /service/**
      serviceId: eureka-service
spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
test: hh
